/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CloudTextResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudTextResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudTextResponse
        //private CloudTextResponse instance;

        public CloudTextResponseTests()
        {
            // TODO uncomment below to create an instance of CloudTextResponse
            //instance = new CloudTextResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudTextResponse
        /// </summary>
        [Fact]
        public void CloudTextResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudTextResponse
            //Assert.IsType<CloudTextResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Paraphrase'
        /// </summary>
        [Fact]
        public void ParaphraseTest()
        {
            // TODO unit test for the property 'Paraphrase'
        }
        /// <summary>
        /// Test the property 'Paraphrases'
        /// </summary>
        [Fact]
        public void ParaphrasesTest()
        {
            // TODO unit test for the property 'Paraphrases'
        }
        /// <summary>
        /// Test the property 'SourceList'
        /// </summary>
        [Fact]
        public void SourceListTest()
        {
            // TODO unit test for the property 'SourceList'
        }
        /// <summary>
        /// Test the property 'TargetList'
        /// </summary>
        [Fact]
        public void TargetListTest()
        {
            // TODO unit test for the property 'TargetList'
        }

    }

}
