/*
 * GroupDocs.Rewriter.Apigateway.Wab
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CloudDetectorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudDetectorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudDetectorResponse
        //private CloudDetectorResponse instance;

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudDetectorResponse
        /// </summary>
        [Fact]
        public void CloudDetectorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudDetectorResponse
            //Assert.IsType<CloudDetectorResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Probability'
        /// </summary>
        [Fact]
        public void ProbabilityTest()
        {
            // TODO unit test for the property 'Probability'
        }
        /// <summary>
        /// Test the property 'IsParaphrased'
        /// </summary>
        [Fact]
        public void IsParaphrasedTest()
        {
            // TODO unit test for the property 'IsParaphrased'
        }
        /// <summary>
        /// Test the property 'PerParagraphProbability'
        /// </summary>
        [Fact]
        public void PerParagraphProbabilityTest()
        {
            // TODO unit test for the property 'PerParagraphProbability'
        }

    }

}
