/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.4.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DetectionSupportedFormats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectionSupportedFormatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectionSupportedFormats
        //private DetectionSupportedFormats instance;

        public DetectionSupportedFormatsTests()
        {
            // TODO uncomment below to create an instance of DetectionSupportedFormats
            //instance = new DetectionSupportedFormats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectionSupportedFormats
        /// </summary>
        [Fact]
        public void DetectionSupportedFormatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectionSupportedFormats
            //Assert.IsType<DetectionSupportedFormats>(instance);
        }



    }

}
