/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DetectionTextResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectionTextResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectionTextResponse
        //private DetectionTextResponse instance;

        public DetectionTextResponseTests()
        {
            // TODO uncomment below to create an instance of DetectionTextResponse
            //instance = new DetectionTextResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectionTextResponse
        /// </summary>
        [Fact]
        public void DetectionTextResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectionTextResponse
            //Assert.IsType<DetectionTextResponse>(instance);
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Probability'
        /// </summary>
        [Fact]
        public void ProbabilityTest()
        {
            // TODO unit test for the property 'Probability'
        }
        /// <summary>
        /// Test the property 'IsParaphrased'
        /// </summary>
        [Fact]
        public void IsParaphrasedTest()
        {
            // TODO unit test for the property 'IsParaphrased'
        }

    }

}
