/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.11.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DetectDocumentPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectDocumentPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectDocumentPostRequest
        //private DetectDocumentPostRequest instance;

        public DetectDocumentPostRequestTests()
        {
            // TODO uncomment below to create an instance of DetectDocumentPostRequest
            //instance = new DetectDocumentPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectDocumentPostRequest
        /// </summary>
        [Fact]
        public void DetectDocumentPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectDocumentPostRequest
            //Assert.IsType<DetectDocumentPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'MinLength'
        /// </summary>
        [Fact]
        public void MinLengthTest()
        {
            // TODO unit test for the property 'MinLength'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'OriginalName'
        /// </summary>
        [Fact]
        public void OriginalNameTest()
        {
            // TODO unit test for the property 'OriginalName'
        }
        /// <summary>
        /// Test the property 'SavingMode'
        /// </summary>
        [Fact]
        public void SavingModeTest()
        {
            // TODO unit test for the property 'SavingMode'
        }

    }

}
