/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing HealthCheckInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HealthCheckInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HealthCheckInfo
        //private HealthCheckInfo instance;

        public HealthCheckInfoTests()
        {
            // TODO uncomment below to create an instance of HealthCheckInfo
            //instance = new HealthCheckInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthCheckInfo
        /// </summary>
        [Fact]
        public void HealthCheckInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HealthCheckInfo
            //Assert.IsType<HealthCheckInfo>(instance);
        }


        /// <summary>
        /// Test the property 'FilesProcessorStatus'
        /// </summary>
        [Fact]
        public void FilesProcessorStatusTest()
        {
            // TODO unit test for the property 'FilesProcessorStatus'
        }
        /// <summary>
        /// Test the property 'ParaphrasingStatus'
        /// </summary>
        [Fact]
        public void ParaphrasingStatusTest()
        {
            // TODO unit test for the property 'ParaphrasingStatus'
        }
        /// <summary>
        /// Test the property 'DetectorStatus'
        /// </summary>
        [Fact]
        public void DetectorStatusTest()
        {
            // TODO unit test for the property 'DetectorStatus'
        }
        /// <summary>
        /// Test the property 'SummarizationStatus'
        /// </summary>
        [Fact]
        public void SummarizationStatusTest()
        {
            // TODO unit test for the property 'SummarizationStatus'
        }

    }

}
