/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Model
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model
        //private Model instance;

        public ModelTests()
        {
            // TODO uncomment below to create an instance of Model
            //instance = new Model();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model
        /// </summary>
        [Fact]
        public void ModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Model
            //Assert.IsType<Model>(instance);
        }


        /// <summary>
        /// Test the property 'Loaded'
        /// </summary>
        [Fact]
        public void LoadedTest()
        {
            // TODO unit test for the property 'Loaded'
        }
        /// <summary>
        /// Test the property 'ModelsId'
        /// </summary>
        [Fact]
        public void ModelsIdTest()
        {
            // TODO unit test for the property 'ModelsId'
        }
        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Fact]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }
        /// <summary>
        /// Test the property 'Opt'
        /// </summary>
        [Fact]
        public void OptTest()
        {
            // TODO unit test for the property 'Opt'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Fact]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'Tokenizer'
        /// </summary>
        [Fact]
        public void TokenizerTest()
        {
            // TODO unit test for the property 'Tokenizer'
        }

    }

}
