/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Opt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Opt
        //private Opt instance;

        public OptTests()
        {
            // TODO uncomment below to create an instance of Opt
            //instance = new Opt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Opt
        /// </summary>
        [Fact]
        public void OptInstanceTest()
        {
            // TODO uncomment below to test "IsType" Opt
            //Assert.IsType<Opt>(instance);
        }


        /// <summary>
        /// Test the property 'BeamSize'
        /// </summary>
        [Fact]
        public void BeamSizeTest()
        {
            // TODO unit test for the property 'BeamSize'
        }
        /// <summary>
        /// Test the property 'Gpu'
        /// </summary>
        [Fact]
        public void GpuTest()
        {
            // TODO unit test for the property 'Gpu'
        }
        /// <summary>
        /// Test the property 'ReplaceUnk'
        /// </summary>
        [Fact]
        public void ReplaceUnkTest()
        {
            // TODO unit test for the property 'ReplaceUnk'
        }

    }

}
