/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ParaphraseTextRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParaphraseTextRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParaphraseTextRequest
        //private ParaphraseTextRequest instance;

        public ParaphraseTextRequestTests()
        {
            // TODO uncomment below to create an instance of ParaphraseTextRequest
            //instance = new ParaphraseTextRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParaphraseTextRequest
        /// </summary>
        [Fact]
        public void ParaphraseTextRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParaphraseTextRequest
            //Assert.IsType<ParaphraseTextRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Texts'
        /// </summary>
        [Fact]
        public void TextsTest()
        {
            // TODO unit test for the property 'Texts'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Suggestions'
        /// </summary>
        [Fact]
        public void SuggestionsTest()
        {
            // TODO unit test for the property 'Suggestions'
        }
        /// <summary>
        /// Test the property 'DiversityDegree'
        /// </summary>
        [Fact]
        public void DiversityDegreeTest()
        {
            // TODO unit test for the property 'DiversityDegree'
        }
        /// <summary>
        /// Test the property 'Tokenize'
        /// </summary>
        [Fact]
        public void TokenizeTest()
        {
            // TODO unit test for the property 'Tokenize'
        }

    }

}
