/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ParaphraseTextResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParaphraseTextResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParaphraseTextResponse
        //private ParaphraseTextResponse instance;

        public ParaphraseTextResponseTests()
        {
            // TODO uncomment below to create an instance of ParaphraseTextResponse
            //instance = new ParaphraseTextResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParaphraseTextResponse
        /// </summary>
        [Fact]
        public void ParaphraseTextResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParaphraseTextResponse
            //Assert.IsType<ParaphraseTextResponse>(instance);
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'ParaphraseReult'
        /// </summary>
        [Fact]
        public void ParaphraseReultTest()
        {
            // TODO unit test for the property 'ParaphraseReult'
        }
        /// <summary>
        /// Test the property 'ParaphraseResults'
        /// </summary>
        [Fact]
        public void ParaphraseResultsTest()
        {
            // TODO unit test for the property 'ParaphraseResults'
        }
        /// <summary>
        /// Test the property 'SourceList'
        /// </summary>
        [Fact]
        public void SourceListTest()
        {
            // TODO unit test for the property 'SourceList'
        }
        /// <summary>
        /// Test the property 'TargetList'
        /// </summary>
        [Fact]
        public void TargetListTest()
        {
            // TODO unit test for the property 'TargetList'
        }

    }

}
