/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SummarizationFileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SummarizationFileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SummarizationFileResponse
        //private SummarizationFileResponse instance;

        public SummarizationFileResponseTests()
        {
            // TODO uncomment below to create an instance of SummarizationFileResponse
            //instance = new SummarizationFileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SummarizationFileResponse
        /// </summary>
        [Fact]
        public void SummarizationFileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SummarizationFileResponse
            //Assert.IsType<SummarizationFileResponse>(instance);
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
