/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Rewriter.Cloud.Sdk.Model;
using GroupDocs.Rewriter.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SupportedConversionsFormats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupportedConversionsFormatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupportedConversionsFormats
        //private SupportedConversionsFormats instance;

        public SupportedConversionsFormatsTests()
        {
            // TODO uncomment below to create an instance of SupportedConversionsFormats
            //instance = new SupportedConversionsFormats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupportedConversionsFormats
        /// </summary>
        [Fact]
        public void SupportedConversionsFormatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupportedConversionsFormats
            //Assert.IsType<SupportedConversionsFormats>(instance);
        }



    }

}
