/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.4.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupDocs.Rewriter.Cloud.Sdk.Client.OpenAPIDateConverter;

namespace GroupDocs.Rewriter.Cloud.Sdk.Model
{
    /// <summary>
    /// Defines FileSavingMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FileSavingMode
    {
        /// <summary>
        /// Enum Files for value: Files
        /// </summary>
        [EnumMember(Value = "Files")]
        Files = 1,

        /// <summary>
        /// Enum Archive for value: Archive
        /// </summary>
        [EnumMember(Value = "Archive")]
        Archive = 2,

        /// <summary>
        /// Enum Both for value: Both
        /// </summary>
        [EnumMember(Value = "Both")]
        Both = 3

    }

}
