/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.11.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupDocs.Rewriter.Cloud.Sdk.Client.OpenAPIDateConverter;

namespace GroupDocs.Rewriter.Cloud.Sdk.Model
{
    /// <summary>
    /// Defines SupportedConversionsFormats
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SupportedConversionsFormats
    {
        /// <summary>
        /// Enum Docx for value: Docx
        /// </summary>
        [EnumMember(Value = "Docx")]
        Docx = 1,

        /// <summary>
        /// Enum Rtf for value: Rtf
        /// </summary>
        [EnumMember(Value = "Rtf")]
        Rtf = 2,

        /// <summary>
        /// Enum Html for value: Html
        /// </summary>
        [EnumMember(Value = "Html")]
        Html = 3,

        /// <summary>
        /// Enum Odt for value: Odt
        /// </summary>
        [EnumMember(Value = "Odt")]
        Odt = 4,

        /// <summary>
        /// Enum Txt for value: Txt
        /// </summary>
        [EnumMember(Value = "Txt")]
        Txt = 5,

        /// <summary>
        /// Enum Md for value: Md
        /// </summary>
        [EnumMember(Value = "Md")]
        Md = 6,

        /// <summary>
        /// Enum Pdf for value: Pdf
        /// </summary>
        [EnumMember(Value = "Pdf")]
        Pdf = 7,

        /// <summary>
        /// Enum Tiff for value: Tiff
        /// </summary>
        [EnumMember(Value = "Tiff")]
        Tiff = 8,

        /// <summary>
        /// Enum Svg for value: Svg
        /// </summary>
        [EnumMember(Value = "Svg")]
        Svg = 9,

        /// <summary>
        /// Enum Xps for value: Xps
        /// </summary>
        [EnumMember(Value = "Xps")]
        Xps = 10,

        /// <summary>
        /// Enum Pptx for value: Pptx
        /// </summary>
        [EnumMember(Value = "Pptx")]
        Pptx = 11,

        /// <summary>
        /// Enum Git for value: Git
        /// </summary>
        [EnumMember(Value = "Git")]
        Git = 12

    }

}
