/*
 * GroupDocs.Rewriter.Apigateway.Wab
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace GroupDocs.Rewriter.Cloud.Sdk.Model
{
    /// <summary>
    /// TextRequest
    /// </summary>
    [DataContract(Name = "TextRequest")]
    public class TextRequest : IEquatable<TextRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextRequest" /> class.
        /// </summary>
        /// <param name="language">Language of original text.</param>
        /// <param name="text">Text to rewrite.</param>
        /// <param name="texts">Text array to rewrite.</param>
        /// <param name="suggestions">Number of suggested variants, 3 maximum.</param>
        /// <param name="diversity">Diversity of text.</param>
        /// <param name="tokenize">Should source and target texts be returned in tokenized form.</param>
        /// <param name="origin">for analysis only.</param>
        public TextRequest(string language = default(string), string text = default(string), List<string> texts = default(List<string>), int suggestions = default(int), string diversity = default(string), bool tokenize = default(bool), string origin = default(string))
        {
            Language = language;
            Text = text;
            Texts = texts;
            Suggestions = suggestions;
            Diversity = diversity;
            Tokenize = tokenize;
            Origin = origin;
        }

        /// <summary>
        /// Language of original text
        /// </summary>
        /// <value>Language of original text</value>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Text to rewrite
        /// </summary>
        /// <value>Text to rewrite</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Text array to rewrite
        /// </summary>
        /// <value>Text array to rewrite</value>
        [DataMember(Name = "texts", EmitDefaultValue = false)]
        public List<string> Texts { get; set; }

        /// <summary>
        /// Number of suggested variants, 3 maximum
        /// </summary>
        /// <value>Number of suggested variants, 3 maximum</value>
        [DataMember(Name = "suggestions", EmitDefaultValue = false)]
        public int Suggestions { get; set; }

        /// <summary>
        /// Diversity of text
        /// </summary>
        /// <value>Diversity of text</value>
        [DataMember(Name = "diversity", EmitDefaultValue = false)]
        public string Diversity { get; set; }

        /// <summary>
        /// Should source and target texts be returned in tokenized form
        /// </summary>
        /// <value>Should source and target texts be returned in tokenized form</value>
        [DataMember(Name = "tokenize", EmitDefaultValue = true)]
        public bool Tokenize { get; set; }

        /// <summary>
        /// for analysis only
        /// </summary>
        /// <value>for analysis only</value>
        [DataMember(Name = "origin", EmitDefaultValue = false)]
        public string Origin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TextRequest {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Texts: ").Append(Texts).Append("\n");
            sb.Append("  Suggestions: ").Append(Suggestions).Append("\n");
            sb.Append("  Diversity: ").Append(Diversity).Append("\n");
            sb.Append("  Tokenize: ").Append(Tokenize).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TextRequest);
        }

        /// <summary>
        /// Returns true if TextRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TextRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TextRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    Language == input.Language ||
                    (Language != null &&
                    Language.Equals(input.Language))
                ) && 
                (
                    Text == input.Text ||
                    (Text != null &&
                    Text.Equals(input.Text))
                ) && 
                (
                    Texts == input.Texts ||
                    Texts != null &&
                    input.Texts != null &&
                    Texts.SequenceEqual(input.Texts)
                ) && 
                (
                    Suggestions == input.Suggestions ||
                    Suggestions.Equals(input.Suggestions)
                ) && 
                (
                    Diversity == input.Diversity ||
                    (Diversity != null &&
                    Diversity.Equals(input.Diversity))
                ) && 
                (
                    Tokenize == input.Tokenize ||
                    Tokenize.Equals(input.Tokenize)
                ) && 
                (
                    Origin == input.Origin ||
                    (Origin != null &&
                    Origin.Equals(input.Origin))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Language != null)
                {
                    hashCode = (hashCode * 59) + Language.GetHashCode();
                }
                if (Text != null)
                {
                    hashCode = (hashCode * 59) + Text.GetHashCode();
                }
                if (Texts != null)
                {
                    hashCode = (hashCode * 59) + Texts.GetHashCode();
                }
                hashCode = (hashCode * 59) + Suggestions.GetHashCode();
                if (Diversity != null)
                {
                    hashCode = (hashCode * 59) + Diversity.GetHashCode();
                }
                hashCode = (hashCode * 59) + Tokenize.GetHashCode();
                if (Origin != null)
                {
                    hashCode = (hashCode * 59) + Origin.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
