/*
 * GroupDocs.Rewriter API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.0
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GroupDocs.Rewriter.Cloud.Sdk.Client;
using GroupDocs.Rewriter.Cloud.Sdk.Api;
using GroupDocs.Rewriter.Cloud.Sdk.Model;

// uncomment below to import models
//using GroupDocs.Rewriter.Cloud.Sdk.Model;

namespace GroupDocs.Rewriter.Cloud.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing SummarizeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SummarizeApiTests : IDisposable
    {
        private SummarizeApi instance;

        public SummarizeApiTests()
        {
            instance = new SummarizeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SummarizeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SummarizeApi
            //Assert.IsType<SummarizeApi>(instance);
        }

        /// <summary>
        /// Test SummarizeDocumentPost
        /// </summary>
        [Fact]
        public void SummarizeDocumentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            var request = new SummarizationFileRequest();
            request.Format = SupportedFormats.Docx;
            request.OutputFormat = SupportedConversionsFormats.Rtf;
            //string outFormat = null;
            //string language = null;
            //System.IO.Stream file = null;
            //string format = null;
            //string url = null;
            //string diversity = null;
            //string origin = null;
            //bool? formatting = null;
            //int? minLength = null;
            //string savingMode = null;
            //var response = instance.SummarizeDocumentPost(outFormat, language, file, format, url, diversity, origin, formatting, minLength, savingMode);
            //Assert.IsType<StatusResponse>(response);
        }

        /// <summary>
        /// Test SummarizeDocumentRequestIdGet
        /// </summary>
        [Fact]
        public void SummarizeDocumentRequestIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //var response = instance.SummarizeDocumentRequestIdGet(requestId);
            //Assert.IsType<CloudFileResponse>(response);
        }

        /// <summary>
        /// Test SummarizeHcGet
        /// </summary>
        [Fact]
        public void SummarizeHcGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SummarizeHcGet();
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test SummarizeTextPost
        /// </summary>
        [Fact]
        public void SummarizeTextPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TextRequest textRequest = null;
            //var response = instance.SummarizeTextPost(textRequest);
            //Assert.IsType<StatusResponse>(response);
        }

        /// <summary>
        /// Test SummarizeTextRequestIdGet
        /// </summary>
        [Fact]
        public void SummarizeTextRequestIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string requestId = null;
            //var response = instance.SummarizeTextRequestIdGet(requestId);
            //Assert.IsType<CloudTextResponse>(response);
        }
    }
}
